name: AutoUpdateProfile

on:
  schedule:
    - cron: '0 4 * * *'

  workflow_dispatch:

jobs:
  UpdateProfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Profile Readme Development Stats
        uses: anmol098/waka-readme-stats@master
        with:
          # GitHub access token with Repo scope
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # default is ${{ github.token }}
          # Your Wakatime API Key
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Show the list of OS Worked on In dev metrics
          # SHOW_OS: False # optional, default is True
          # Show the list of projects worked on in dev metrics
          SHOW_PROJECTS: False # optional, default is True
          # Show the Editors used in dev metrics
          # SHOW_EDITORS: # optional, default is True
          # Show the time zone in the dev metrics
          # SHOW_TIMEZONE: False # optional, default is True
          # Shows the number of commit graph in the dev metrics
          SHOW_COMMIT: False # optional, default is True
          # Show the Coding language used in dev metrics
          # SHOW_LANGUAGE: # optional, default is True
          # Show the Total Lines of code written Badge till date
          # SHOW_LINES_OF_CODE: # optional, default is False
          # Show language or framework used across different repository
          SHOW_LANGUAGE_PER_REPO: False # optional, default is True
          # 
          SHOW_LOC_CHART: False # optional, default is True
          # show day of week you are most productive
          SHOW_DAYS_OF_WEEK: False # optional, default is True
          # Shows the current profile views
          SHOW_PROFILE_VIEWS: False # optional, default is True
          # Shows the short facts
          SHOW_SHORT_INFO: False # optional, default is True
          # Show stats in your own language
          # LOCALE: # optional, default is en
          
          SHOW_TOTAL_CODE_TIME: False
